-- İmza tablosu
CREATE TABLE signatures (
    id INT AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    file_size INT NOT NULL,
    signature_format VARCHAR(50) NOT NULL,
    certificate_name VARCHAR(255),
    certificate_issuer VARCHAR(255),
    certificate_serial_number VARCHAR(100),
    signature_date DATETIME,
    signature_location VARCHAR(255),
    signature_reason VARCHAR(255),
    pdf_signature_pos_x INT,
    pdf_signature_pos_y INT,
    pdf_signature_width INT,
    pdf_signature_height INT,
    signature_data TEXT,
    ip_address VARCHAR(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status ENUM('pending', 'completed', 'failed') DEFAULT 'pending',
    error_message TEXT,
    signed_pdf_path VARCHAR(255),
    signature_chain JSON,
    required_signatures INT DEFAULT 1,
    completed_signatures INT DEFAULT 0,
    next_signer VARCHAR(255),
    signature_deadline DATETIME,
    signature_groups JSON,
    current_group INT DEFAULT 1,
    group_signatures JSON,
    group_status JSON,
    signature_type ENUM('chain', 'parallel', 'mixed') DEFAULT 'chain',
    INDEX idx_filename (filename),
    INDEX idx_certificate_serial (certificate_serial_number),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    INDEX idx_next_signer (next_signer),
    INDEX idx_current_group (current_group)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Users tablosu
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    email VARCHAR(255),
    role ENUM('admin', 'user') DEFAULT 'user',
    last_login DATETIME,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_username (username),
    INDEX idx_role (role)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;